
source 'https://github.com/CocoaPods/Specs.git'

platform:ios, '8.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '4.0'
            config.build_settings['ARCHS'] = 'armv7 arm64'
            if config.name == 'Debug'
                config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end
end


target 'KWSModule_Example' do
    pod 'KWSModule', :path => '../'
    
    pod 'YZJAPPModule', :path => '../../YZJAPPModule'
    
    target 'KWSModule_Tests' do
        inherit! :search_paths
        
        
    end
end
